version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=db:3306
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
    depends_on:
      - db
    volumes:
      - grafana_data:/var/lib/grafana

  db:
    image: mysql:5.7
    container_name: grafana-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=grafana
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=grafana
    volumes:
      - db_data:/var/lib/mysql

volumes:
  grafana_data:
  db_data:
