services:
    consul:
        image: consul:1.15.4
        ports:
          - "8500:8500"   
          - "8600:8600"   
          - "8300:8300"   
          - "8301:8301"   
          - "8302:8302"   
        command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
        volumes:
          - ./data:/consul/data
        networks:
          - pi-net

networks:
  pi-net:
    driver: bridge
